config/routes.rb
Biomodis::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: "devise2/registrations" }
  get "models/visor"
  get "models/download_model"
  get "species/species_content"
  get "species/species_models"
  get "users/edit_profile"
  get "comments/child_comments"
  get "home/feedback"
  post "home/send_message"
  get "home/groups"
  post "ratings/rate_model"
  post "species/comment_point"
  post "species/create_comment_point"
  post "groups/bulk_email"
  post "groups/email_invitation"
  post "species/species_by_class"
  post "species/add_ecological_variable"
  post "species/add_altitude_range"
  post "reviews/reviews_by_species"
  post "regions/save_region_user"
  post "species/get_altitude_range"
  resources :regions do
    get :regions_by_user, :on => :collection
  end
  resources :ratings, only: :update
  resources :comments, :only => [:create, :destroy, :edit, :update]
  resources :home, :only => [:show]
  resources :reviews, :only => [:show, :create, :destroy]
  resources :users, :only => [:show, :edit, :update]
  resources :user_relationships, :only => [:create]
  resources :models, :only => [:index, :new, :create]
  resources :species, :only => [:new, :create, :edit] do
    get :autocomplete, :on => :collection
    get :regions_autocomplete, :on => :collection
    get :eco_variables_search, :on => :collection
  end 
  resources :faq, :only => [:index]
  resources :groups do
  end
  resources :species_groups, :only => [:index, :create, :update]
  resources :group_users do
  end

  root 'home#show'

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates :body, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_votable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
  	@comment_hash = params[:comment]
  	if (params[:comment].has_key?(:parent_id) && !params[:comment][:parent_id].blank?)
    	@parent = Comment.find(params[:comment][:parent_id])
	end
  	@obj = @comment_hash[:commentable_type].constantize.find(@comment_hash[:commentable_id])
  	 # Not implemented: check to see whether the user has permission to create a comment on this object
  	@comment = Comment.build_from(@obj, current_user.id, @comment_hash[:body])

  	if @comment.save
        # render :partial => "comments/comment", :locals => { :comment => @comment }, :layout => false, :status => :created
        if @parent
        	@comment.move_to_child_of(@parent)
      	end
        respond_to do |format|
        	format.js
        end
    else
        render :js => "alert('error saving comment');"
    end
  end

  def child_comments
  	@id_parent = params[:parent_id]
  	#@post = Post.find(params[:post_id])
  	#@new_comment = Comment.build_from(@post, current_user, '')

  	respond_to do |format|
  		format.html
        format.js
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_edit.html.erb
<%= form_for @comment, :remote => true, :id => 'edit-comment-form' do |f| %>
		<!--  <%= f.hidden_field :comment_id, :value => @comment_id, :id => 'comment-parent-field' %> -->
		 <%= f.text_area :body, :class => 'commeinput', :placeholder => 'Comentario', :value => @comment.body %>
	     <%= f.submit :submit, :disable_with => "Submitting…", :class => 'reply replyfl replybotoon', :value => 'Guardar' %>
<% end %>

app/views/comments/_new.html.erb
<div class='comment-form'>
	<%= form_for new_comment, :remote => true, :id => 'new-comment-form' do |f| %>
		 <%= f.hidden_field :parent_id, :value => @id_parent, :id => 'comment-parent-field' %>
		 <%= f.text_area :body, :class => 'commeinput', :placeholder => 'Comentario' %>
	     <%= f.hidden_field :commentable_id, :value => new_comment.commentable_id %>
	     <%= f.hidden_field :commentable_type, :value => new_comment.commentable_type %>
	     <%= f.submit :submit, :disable_with => "Submitting…", :class => 'cbton', :value => 'comentar' %>
	<% end %>
</div>

app/views/comments/_show.html.erb
<%= content_tag :div, :id => "comment-#{comment.id}", :class => 'comment-tab' do %>
	<div class="minavatar"><%= image_tag("minavatar.png") %></div>
		<%= link_to User.find(comment.user_id).name, root_url + 'users/'+ comment.user_id.to_s, {:class => 'feeduserp' } %>
		<div class="feedtimep"><%= comment.updated_at %></div>
		<%= link_to 'Reply', comments_child_comments_path(:parent_id => comment.id), :remote => true, :class => 'reply' %>
		<p class="feedcontentp"><%= comment.body %></p>

		<% if comment.has_children? %>
			<%= render :partial => 'comments/show', :collection => comment.children, :as => :comment %>
		<% end %>
<% end %>

app/views/comments/child_comments.js.erb
$('#comment_body').attr("placeholder", "Respondiendo mensaje a <%=j User.find(Comment.find(@id_parent).user_id).name %>");
if('<%= @id_parent %>') $('#comment-parent-field').val('<%= @id_parent %>');
$('#comment_body').focus();

app/views/comments/create.js.erb
if ('<%= @comment.parent_id %>') $('#comment-<%= @comment.parent_id %>').append('<%=j render partial: 'comments/show', :locals => { :comment => @comment }  %>');
else $('.comments-list').prepend('<%=j render partial: 'comments/show', :locals => { :comment => @comment }  %>');

$('#new_comment').trigger('reset');
$('#comment-parent-field').val('');

app/views/comments/destroy.js.erb
$.ajax({
    type: "GET",
    url: "/species/species_models",
    data: { species_id: <%= @comment.commentable_id %>}
});

app/views/comments/edit.js.erb
$("#comment-" + <%= @comment.id %>).find("div.comment-space").html('<%=j render partial: 'comments/edit' %>');
$("#comment-" + <%= @comment.id %>).find("div.btn-edit-cmt").html('<%= link_to "Cancelar", :back, :class => "reply replyfl", :id => "cancel-btn-cmt" %>');
$("#comment-" + <%= @comment.id %>).find("div.btn-reply-cmt").html('');
$("body").on("click", "#cancel-btn-cmt", function (e) {
	e.preventDefault();
	$.ajax({
	    type: "GET",
	    url: "/species/species_models",
	    data: { species_id: <%= @comment.commentable_id %>}
	});
});

app/views/comments/update.js.erb
$.ajax({
    type: "GET",
    url: "/species/species_models",
    data: { species_id: <%= @comment.commentable_id %>}
});