config/routes.rb
Biomodis::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: "devise2/registrations" }
  get "models/visor"
  get "models/download_model"
  get "species/species_content"
  get "species/species_models"
  get "users/edit_profile"
  get "comments/child_comments"
  get "home/feedback"
  post "home/send_message"
  get "home/groups"
  post "ratings/rate_model"
  post "species/comment_point"
  post "species/create_comment_point"
  post "groups/bulk_email"
  post "groups/email_invitation"
  post "species/species_by_class"
  post "species/add_ecological_variable"
  post "species/add_altitude_range"
  post "reviews/reviews_by_species"
  post "regions/save_region_user"
  post "species/get_altitude_range"
  resources :regions do
    get :regions_by_user, :on => :collection
  end
  resources :ratings, only: :update
  resources :comments, :only => [:create, :destroy, :edit, :update]
  resources :home, :only => [:show]
  resources :reviews, :only => [:show, :create, :destroy]
  resources :users, :only => [:show, :edit, :update]
  resources :user_relationships, :only => [:create]
  resources :models, :only => [:index, :new, :create]
  resources :species, :only => [:new, :create, :edit] do
    get :autocomplete, :on => :collection
    get :regions_autocomplete, :on => :collection
    get :eco_variables_search, :on => :collection
  end 
  resources :faq, :only => [:index]
  resources :groups do
  end
  resources :species_groups, :only => [:index, :create, :update]
  resources :group_users do
  end

  root 'home#show'

  

end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  def index
  end

  def autocomplete
    species = Species.search(params[:query], params[:classId])
    result = species.collect do |t|
      { value: t.sci_name, id: t.id }
    end

    render json: result
  end  

  def species_content

    if params[:species_id].blank?
      @species = nil
    else
      @species = Species.find(params[:species_id])
    end

    respond_to do |format|
      format.js
    end
  end

  def species_models

    if params[:species_id].blank?
      @species = nil
    else
      @species = Species.find(params[:species_id])
      @models = Model.where(:species_id => params[:species_id], current: true).limit(10)
      @all_comments = @species.root_comments.order('created_at desc')

      arr = []
      @ratings = Hash.new 

      @models.each do |m|
        arr.push(m.id)
        if user_signed_in?
          @rating = Rating.where(model_id: m.id, user_id: current_user.id).first
          @ratings[m.id] = @rating.blank? ? 0 : @rating.score
        end
      end

      @species_reviews = Review.where({ model_id: arr}).order("created_at DESC")

      if user_signed_in?
        @new_comment = Comment.build_from(@species, current_user.id, '')
      end
    end

    respond_to do |format|
      format.js
    end
  end

  def show
    @species = Species.find(params[:id])
    # render :partial=>'show'

    respond_to do |format|
      # format.html {render :partial => 'show'}
      format.js   # show_rec_horses.js.erb
    end
   
  end

  def new
    @species = Species.new
  end

  def create
    @species = Species.new(species_params)
    if @species.save
      flash[:sci_name] = 'Species created!!!'
      redirect_to new_species_path
    else
      render :action => "new"
    end
  end

  def comment_point
    @point_comment = PointComment.new

    respond_to do |format|
      format.js
    end
  end

  def create_comment_point
    @point_comment = PointComment.new(point_comment_params)
    if @point_comment.save
      flash[:success] = 'Anotación guardada con éxito.'
    else
      flash[:error] = 'Ha ocurrido un error mientras se guardaba la anotación.'
    end

     respond_to do |format|
        format.html
        format.js
     end
  end

  def workshop_test
    @workshop_test = WorkshopTest.new

    respond_to do |format|
      format.js
    end
  end

  def create_workshop_test
    @workshop_test = WorkshopTest.new(workshop_test_params)

    if @workshop_test.save
      flash[:success] = 'Anotación guardada con éxito.'
    else
      flash[:error] = 'Ha ocurrido un error mientras se guardaba la anotación.'
    end

     respond_to do |format|
        format.html
        format.js
     end
  end

  def update
  end

  private

    def species_params
      params.require(:species).permit(:class_id, :sci_name, :order, :family, :sib_url, :ocurrence_records)
    end

    def point_comment_params
      params.require(:point_comment).permit(:user_id, :species_id, :lat, :lon, :wrong_id, :geo_problem, :comment)
    end

    def workshop_test_params
      params.require(:workshop_test).permit(:user_id, :species_id, :lat, :lon, :min_ocurrence, :max_ocurrence, :best_prob_ocurrence, :certainty_true_value)
    end
end

app/helpers/species_helper.rb
module SpeciesHelper
	def get_species_name
  		Species.uniq.pluck(:sci_name)    
	end

	def file_exists(modelId)
		filepath = Rails.root.join('public/kmz/'+ Model.find(modelId).img_url.split('.').first + '.kmz')
		if File.exists?(filepath)
          true
        else
          false
        end
	end

	def get_models_array (models)
	end
end

app/views/species/_search_form.html.erb
<%= form_tag({:controller => :species, :action => :species_models}, {:method => :get, :remote => true, :id => 'sp_search_form'})  do %>
  <%= text_field_tag :query, '', :id => 'search_field', :placeholder => 'Ingrese nombre de la especie', :collection => 'get_species_name', :include_blank => false, :rel => 'autocomplete' %>
  <%= hidden_field_tag 'species_id' %>
  <%= submit_tag '', :name => nil, :class => 'searchbtn', :id => 'species_src_btn' %>
<% end %>

<p class="clearfix">Busqueda por nombre científico.</p>

app/views/species/_species_by_class.html.erb
<% @species.each do |species|%>
	<%= link_to species.sci_name, species_species_models_path(:species_id => species.id, :name => species.sci_name), :remote => true%><br />
<% end %>

app/views/species/_species_content.html.erb
<% if @species.blank? %>
	<p class="textsrch">No se encontraron resultados.</p>
<% else %>
	<div class="mbton">ver modelos</div>
	<%= link_to 'ver modelos', species_species_models_path(:id => @species.id, :name => @species.sci_name), :remote => true, :class => "mbton"%>
	<div class="resbusqueda">
				<div class="especie"><%= @species.sci_name %></div>
				<!-- <div class="comun">Nombre Común:<strong>Tucán</strong></div> -->
	</div>
	
<% end %>


<script>
	// $(".mbton").click(function(e){
 //          $('.selectores,.cajabusqueda').hide('slow');
 //          $('.showmodels').show('slow');
 //          e.preventDefault();
 //  	});
</script>

app/views/species/_species_models.html.erb
<h1><%= @species.sci_name %></h1>
        <div class="registros">
                    <h4>No. Registros</h4>
                    <div class="noreg"><%= @species.ocurrence_records %></div>
                    <div class="clearfix"></div>
                    <% if @species.ocurrence_records_url? %>
                        <%= link_to "Metadatos", root_url + 'metadata/'+ @species.ocurrence_records_url.split('.').first + '.html', {:target => '_blank', :class => 'verreg' } %>
                    <% end %>               
        </div>  
        <div class="resbusqueda genero clearfix"><%= @species.order %></br>
        <div class="familia"><%= @species.family %></div>
        <a href="http://www.biodiversidad.co/" class="linksib" target="_blank">www.biodiversidad.co</a></div>
        <div class="selector hs">
            <div class="left-arrow">
                <a href="#prev">
                </a>
            </div>
            <div class="showcase">
                <ul class="modelost">
                    <% @models.each_with_index do |model, i| %>
                        <li class="modelothumb">
                            <div class="cajadatosm">
                            <%= link_to "#", :class => 'model_link' do%>
                                <%= hidden_field_tag('imgsrc', model.img_url) %>
                                <%= image_tag("/thumbs/"+ model.thumb_url, :height => 205, :width => 145, :id => model.id) %>
                                <div class="modeldata">
                                <h5>Modelo Nivel 1</h5>
                                <h6><b>CORTE: </b></br>
                                <%= model.description %></h6>
                                <p>Promedio:</p>
                                <h3><%= model.average_rating %></h3>
                                <p>Votos: (<%= model.total_votes %>)</p>
                                </div>
                            <% end %>
                            </div>
                            <div class="rankmod clearfix">
                                <% if user_signed_in? %>
                                    <div class="user_star">
                                        <%= hidden_field_tag('model', model.id, :class => 'mid' )  %>
                                        <%= hidden_field_tag('myscore', @ratings[model.id], :class => 'myscore')  %>
                                    </div>
                                <% end %>
                                <% if file_exists(model.id) %>
                                    <%= link_to models_download_model_path(:m_id => model.id), :class => 'download', :remote => true do %>
                                        <%= image_tag("descargar.png") %>
                                    <% end %>
                                <% end %>
                            </div>
                        </li>
                    <% end %>
                </ul>
            </div>
            <div class="right-arrow">
                <a href="#next">
                </a>
            </div>
        </div>

        <p>Seleccionar modelo, calificar o comentar sobre los distintos modelos.<br/>Sobre uno específico dar el nombre del corte.<br/></p>

        <div class="commentspace">
        <h3>Comentarios sobre esta especie y sus modelos</h3>
        <% if user_signed_in? %>
            <%= render :partial => 'comments/new', :locals => {:new_comment => @new_comment} %>
        <% end %>
        </div>
        <div class='comments-list padmodelos'>
            <%= render :partial => 'comments/show', :collection => @all_comments, :as => :comment %>
        </div>
<div class ="termbox"></div>
<script>
$(document).ready(function () {

            $('.model_link').click(function (event) {
                _mapVisorModule.loadModel("/modelos/"+$(this).find('#imgsrc').val());
                $("#review_model_id").val($(this).find('img').attr('id'));
                $('.editControls,.edicionbar').show('slow');
                $('.showmodels, .cajabusqueda, .selectores').hide ('slow');
                event.preventDefault(); // Prevent link from following its href
            });

            $('.user_star').raty({ 
                path: '../assets',
                hints: ['No representa', 'Representa pobremente', 'Representa regularmente', 'Representa adecuadamente', 'Representa muy bien'],
                score:  function() {
                            return $(this).find('.myscore').val();
                },
                click: function(score, evt) {
                    $.ajax({
                        type: "POST",
                        url: "/ratings/rate_model",
                        data: { mid: $(this).find('.mid').val(), score: score }
                    }); 
                } 
            });

});
</script>

<script type="text/javascript">
$(document).ready(function () {
    var div = $('div.showcase');
    var liNum = $(div).find('ul').children('li').length;
    var speed = 1000;
    var containerWidth = 682;
    var itemWidth = 165;
    $(div).css({overflow: 'hidden'});
    $('div.right-arrow').click(function(e){ 
        if(($(div).scrollLeft()+containerWidth)<(liNum*itemWidth)){
            $(div).animate({
                scrollLeft: '+='+containerWidth
            }, speed);
        }
    }); 
    $('div.left-arrow').click(function(e){  
        if(($(div).scrollLeft()+containerWidth)>containerWidth){
            $(div).animate({
                scrollLeft: '-='+containerWidth
            }, speed);
        }
    });
});
</script>

<script>

$(document).ready(function(){
    $('.cajadatosm').mouseenter(function(e){
        $(this).animate({scrollTop:$(".cajadatosm").scrollTop() + $(".modeldata").position().top},600);
        });
    $('.cajadatosm').mouseleave(function(e){
        $(this).animate({scrollTop:$(".cajadatosm").position().top - '20px'},600).finish();
        });
});

</script>

app/views/species/_workshop_test.html.erb
<%= simple_form_for @workshop_test, :url => species_create_workshop_test_path, :method => :post, :remote => true, :html => {:class => "pointcomm" } do |f| %>
	<%= f.input :user_id, :as => :hidden, :input_html => {:value => get_current_user_id} %>
	<%= f.input :species_id, :as => :hidden %>
	<%= f.input :lat, :as => :hidden %>
	<%= f.input :lon, :as => :hidden %>
	<%= f.input :min_ocurrence, :as => :string, :placeholder => "valores entre 0 y 1", :label => "1. Probabilidad de ocurrencia mínima" %>
	<%= f.input :max_ocurrence, :as => :string, :placeholder => "valores entre 0 y 1", :label => "2. Probabilidad de ocurrencia máxima"  %>
	<%= f.input :best_prob_ocurrence, :as => :string, :placeholder => "valores entre 0 y 1", :label => "3. Mejor estimativo de probabilidad de ocurrencia"  %>
	<%= f.input :certainty_true_value, :as => :string, :placeholder => "valores entre 0.5 y 1", :label => "4. Certeza que el rango provisto contiene el valor verdadero"  %>
	<%= f.button :submit, :value => "enviar", :class => 'cbton'%>
	<%= link_to "X", '', {:id => 'cancel-point-cmt', :class => "cancterm"} %>
<% end %>

app/views/species/comment_point.js.erb
$(".pointBox").html(""); //Clear div before rendering again
<% if user_signed_in? %>
	$('.pointBox').html('<%=j render partial: 'species/comment_point', locals: { :point_comment => @point_comment } %>');
	/* Set lat & lon points*/
	$('#point_comment_species_id').val($('#species_id').val());
	$('#point_comment_lat').val($('#point_lat').html());
	$('#point_comment_lon').val($('#point_lon').html());
	/* Cancel button */
	$("#cancel-point-cmt").click(function(e){
		e.preventDefault();
		$(".pointBox").html("");
	});
<% else %>
	alert("Debe estar registrado para poder reportar un registro");
<% end %>

app/views/species/create_workshop_test.js.erb
$(".pointBox").html("");
alert('Guarado con éxito.');

app/views/species/index.html.erb
<h1>Species#index</h1>
<p>Find me in app/views/species/index.html.erb</p>

app/views/species/species_by_class.js.erb
$('.resultados').html('<%=j render partial: 'species/species_by_class' %>');

app/views/species/species_content.js.erb
$('.resultados').html('<%=j render partial: 'species/species_content', locals: { :species => @species } %>');

app/views/species/species_models.js.erb
<% if !@species.blank? %>
	$('.selectores,.cajabusqueda').hide('slow');
	$('.showmodels').show('slow');
	$('.botonmodelos').show('slow');
	$('.showmodels').html('<%=j render partial: 'species/species_models', locals: { :species => @species } %>');
	$('.cajaediciones').html('<%=j render partial: 'reviews/reviews_by_species' %>');
	<% if !@species.ocurrence_records_url.blank? %>
		_mapVisorModule.loadPoints('/registros/' + '<%= @species.ocurrence_records_url %>');
	<% end %>
<% else %>
	$('.resultados').html('No se encontraron resultados');
<% end %>

app/views/species/update.html.erb
<h1>Species#update</h1>
<p>Find me in app/views/species/update.html.erb</p>

app/views/species/workshop_test.js.erb
$(".pointBox").html(""); //Clear div before rendering again
<% if user_signed_in? %>
	$('.pointBox').html('<%=j render partial: 'species/workshop_test', locals: { :workshop_test => @workshop_test } %>');
	$('#workshop_test_species_id').val($('#species_id').val());
	$('#workshop_test_lat').val($('#point_lat').html());
	$('#workshop_test_lon').val($('#point_lon').html());
	$("#cancel-point-cmt").click(function(e){
		e.preventDefault();
		$(".pointBox").html("");
	});
<% else %>
	alert("Debe estar registrado para poder participar");
<% end %>