config/routes.rb
Biomodis::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: "devise2/registrations" }
  get "models/visor"
  get "models/download_model"
  get "species/species_content"
  get "species/species_models"
  get "users/edit_profile"
  get "comments/child_comments"
  get "home/feedback"
  post "home/send_message"
  get "home/groups"
  post "ratings/rate_model"
  post "species/comment_point"
  post "species/create_comment_point"
  post "groups/bulk_email"
  post "groups/email_invitation"
  post "species/species_by_class"
  post "species/add_ecological_variable"
  post "species/add_altitude_range"
  post "reviews/reviews_by_species"
  post "regions/save_region_user"
  post "species/get_altitude_range"
  resources :regions do
    get :regions_by_user, :on => :collection
  end
  resources :ratings, only: :update
  resources :comments, :only => [:create, :destroy, :edit, :update]
  resources :home, :only => [:show]
  resources :reviews, :only => [:show, :create, :destroy]
  resources :users, :only => [:show, :edit, :update]
  resources :user_relationships, :only => [:create]
  resources :models, :only => [:index, :new, :create]
  resources :species, :only => [:new, :create, :edit] do
    get :autocomplete, :on => :collection
    get :regions_autocomplete, :on => :collection
    get :eco_variables_search, :on => :collection
  end 
  resources :faq, :only => [:index]
  resources :groups do
  end
  resources :species_groups, :only => [:index, :create, :update]
  resources :group_users do
  end

  root 'home#show'

  

end

app/views/shared/_error_messages.html.erb
_error_messages.html.erb

app/views/shared/_footer.html.erb
<footer>
	<div class="contenedor">
		<nav>
			<ul id="subnav">
			  <div class="faq"><%= link_to 'faq', faq_index_path %></div>	
			  <div class="faq">
			  	<a data-lightbox="image-1" href="../assets/tutorial1.png" id="tututo">TUTORIAL</a>
			  </div>
			  <div class="faq"><%= link_to 'contacto', home_feedback_path %></div>
			</ul>
		</nav>
		<div class="lbabfooter">
				<div class="textft">
				<h1><strong>Programa de Gestión de Información y Conocimiento</strong></h1>
				<h1><a href="http://humboldt.org.co/investigacion/centro-de-analisis-y-sintesis/laboratorio-2" target="_blank">Laboratorio de Biogeografía Aplicada y Bioacústica (LBAB)</a></h1>
				</div>
		</div>
	</div>
	<a data-lightbox="image-1" href="../assets/tutorial2.png"></a>
	<a data-lightbox="image-1" href="../assets/tutorial3.png"></a>
	<a data-lightbox="image-1" href="../assets/tutorial4.png"></a>
	<a data-lightbox="image-1" href="../assets/tutorial5.png"></a>
	<a data-lightbox="image-1" href="../assets/tutorial6.png"></a>
	<a data-lightbox="image-1" href="../assets/tutorial7.png"></a>

	<script type="text/javascript">
	// //<![CDATA[

	// function createCookie(name,value,days) {
	//   if (days) {
	//     var date = new Date();
	//     date.setTime(date.getTime()+(days*24*60*60*1000));
	//     var expires = "; expires="+date.toGMTString();
	//   }
	//   else var expires = "";
	//   document.cookie = name+"="+value+expires+"; path=/";
	// }

	// function readCookie(name) {
	//   var nameEQ = name + "=";
	//   var ca = document.cookie.split(';');
	//   for(var i=0;i < ca.length;i++) {
	//     var c = ca[i];
	//     while (c.charAt(0)==' ') c = c.substring(1,c.length);
	//     if (c.indexOf(nameEQ) == 0) return c.substring(nameEQ.length,c.length);
	//   }
	//   return null;
	// }

	// function showModal() {
	//   $("#tututo").click();
	// }

	// var visited = readCookie('mypopup');

	// if (!visited) {
	//   $(document).ready(function(){
	//     showModal();
	//     createCookie('mypopup','no',0);
	//   });
	// }

	// //]]>

	// Google Analytics//
	 (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	 (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	 m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	 })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	 ga('create', 'UA-50977245-1', 'humboldt.org.co');
	 ga('send', 'pageview');

	</script>
</footer>

app/views/shared/_header.html.erb
<header class="main clearfix">
	<div class="contenedor clearfix">
		<a href="http://www.humboldt.org.co" class="humbcolor" target="_blank"><%= image_tag("humbcolor.png") %></a>
		<div class="humbimg">
		Instituto de Investigación de Recursos Biológicos<br> 
		Alexander von Humboldt Colombia<br>
		<p>Programa de Gestión de Información y Conocimiento</p>
		</div>
		<%= image_tag("beta.png", :title => 'Versión Beta', :class => 'betaimg' ) %>
		<nav>
			<ul id="subnav">
			  <li>
			    <%= link_to 'Inicio', root_path %>
			  </li>
			  <li>
			    <%= link_to 'Modelos', models_visor_path %>
			  </li>
			  <% if user_signed_in? %>
			    <li><%= link_to 'Perfil', user_path(:id => current_user.id) %></li>
			    <li><%= link_to 'Salir', destroy_user_session_path, :method=>'delete' %></li>
			  <% else %>
			    <li><%= link_to 'Ingresar', new_user_session_path %></li>
			    <li><%= link_to 'Registrarse', new_user_registration_path %></li>
			  <% end %>
			</ul>
		</nav>
	</div>
</header>

<script>
	$(document).ready(function(){
    $('#subnav a').each(function(index) {
        if(this.href.trim() == window.location)
            $(this).addClass("current");
    });
});
</script>

app/views/shared/_sign_in.html.erb
<section class="contenedor">
	<%= simple_form_for(resource, :html => {:class => 'formalogin' }, :as => resource_name, :url => session_path(resource_name)) do |f| %>
    <%= f.input :email, :required => true, :autofocus => true, label: false, :placeholder => "Usuario* (email de registro)", :input_html => { :class => "inputforma" } %>
    <%= f.input :password, :required => true, label: false, :placeholder => "Contraseña*", :input_html => { :class => "inputforma" } %>
    <%= f.input :remember_me, inline_label: ' Recordarme', label: false, :input_html => { :class => "checkrec" }, :as => :boolean if devise_mapping.rememberable? %>
    <%= f.button :button, "ingresar", :class => "bbton" %>
    <div class="clearfix"></div><!--links float-->
	<%= render "devise/shared/links" %>
<% end %>
</section>