config/routes.rb
Biomodis::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: "devise2/registrations" }
  get "models/visor"
  get "models/download_model"
  get "species/species_content"
  get "species/species_models"
  get "users/edit_profile"
  get "comments/child_comments"
  get "home/feedback"
  post "home/send_message"
  get "home/groups"
  post "ratings/rate_model"
  post "species/comment_point"
  post "species/create_comment_point"
  post "groups/bulk_email"
  post "groups/email_invitation"
  post "species/species_by_class"
  post "species/add_ecological_variable"
  post "species/add_altitude_range"
  post "reviews/reviews_by_species"
  post "regions/save_region_user"
  post "species/get_altitude_range"
  resources :regions do
    get :regions_by_user, :on => :collection
  end
  resources :ratings, only: :update
  resources :comments, :only => [:create, :destroy, :edit, :update]
  resources :home, :only => [:show]
  resources :reviews, :only => [:show, :create, :destroy]
  resources :users, :only => [:show, :edit, :update]
  resources :user_relationships, :only => [:create]
  resources :models, :only => [:index, :new, :create]
  resources :species, :only => [:new, :create, :edit] do
    get :autocomplete, :on => :collection
    get :regions_autocomplete, :on => :collection
    get :eco_variables_search, :on => :collection
  end 
  resources :faq, :only => [:index]
  resources :groups do
  end
  resources :species_groups, :only => [:index, :create, :update]
  resources :group_users do
  end

  root 'home#show'

  

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    if user_signed_in?
      user=User.find_by_id(current_user.id)
      if user.group_id != 0 && user.group_id != nil
        group_user = GroupUser.new
        group_user.group_id = user.group_id
        group_user.group_user_state_id=2
        group_user.user_id=user.id
        group_user.is_admin=1
        if group_user.save
          user.group_id=nil
          user.save
        end
      end
      if user.requested_group_name != '' && user.requested_group_name != nil
        group = Group.new
        group.name = user.requested_group_name
        group.description = user.requested_group_name
        group.email = user.email
        group.link = ''
        group.group_state_id=2
        if group.save
          group_user2 = GroupUser.new
          group_user2.user_id = user.id
          group_user2.group_id=group.id
          group_user2.group_user_state_id=1
          group_user2.is_admin=1
          group_user2.save
          user.requested_group_name=''
          user.save
        end
      end
    end
  end

  def send_message
  	@message = Message.new(message_params)
  	ContactMailer.contact_us(@message).deliver

  	respond_to do |format|
  		format.js
  	end
  end

  def groups

    avesexp_ids = [87,78,73,86,74,77,79,80,85,82,68,84,23,89,88,81,83,21,28,22,26,25,32,19,24]
    herpexp_ids = [179,173,169,168,170,178,176,174,175,172,177,171,154,181]
    mamexp_ids = [142,137,152,143,139,138,145,127,141,144,147,146,140,149,148]
    pecesexp_ids = [183, 185, 184, 186, 164, 187, 188]

    @aves_experts = User.find(avesexp_ids)
    @aves_experts.sort! { |a,b| a.name.downcase <=> b.name.downcase }
    

    @herpetos_experts = User.find(herpexp_ids)
    @herpetos_experts.sort! { |a,b| a.name.downcase <=> b.name.downcase }

    @mamiferos_experts = User.find(mamexp_ids)
    @mamiferos_experts.sort! { |a,b| a.name.downcase <=> b.name.downcase }

    @peces_experts = User.find(pecesexp_ids)
    @peces_experts.sort! { |a,b| a.name.downcase <=> b.name.downcase }


  end

  private

    def message_params
      params.require(:message).permit(:name, :email, :subject, :content)
    end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/feedback.html.erb
<div class="bg4">
	<div class="contacto">
	<div class="mailimg"></div>
	              <h2>Mantengase en contacto con nosotros, estamos para atender sus dudas, oir sus opiniones y sugerencias.</h2>
            <div id="mailform">       
                  <%= simple_form_for :message, :url => {:controller => "home", :action => "send_message" }, :html => {:class => 'forma' }, :remote => true do |f| %>
                        <%= f.input :name, :maxlength => 50, :placeholder => "Nombre o Institución", :name => "nombre", label: false%>
                        <%= f.input :subject, :maxlength => 50, :placeholder => "Asunto", :name => "asunto", label: false %>
                        <%= f.input :email, :maxlength => 50, :placeholder => "E-mail", :name => "email", label: false %>
                        <%= f.input :content, :as => :text, :input_html => {:maxlength => 1200, :cols => "20", :rows => "12"}, :name => "cuerpo", label: false %>
                        <%= f.button :submit, :value => "ENVIAR", :class => 'boton1'%>
                  <% end %>
                  <p><strong>Dirección:</strong> calle 28A no. 15-09 Bogotá D.C., Colombia.</br>
                  <strong>Teléfono:</strong> pbx 57(1) 320 2767</br>
                  <a href="mailto:biomodelos@humboldt.org.co">biomodelos@humboldt.org.co</a></p>
            </div>
	</div>
</div>

app/views/home/groups.html.erb
<div class="fondo3 fondo5">
	<article class="faqshow w600">
		<div class="faqtitle clearfix">
			<h1>Grupos de expertos</h1></div>
			<div class="qya">
				<div class="ilb">
				<h3>Grupo Expertos en Aves Acuáticas:</h3>

				<% @aves_experts.each do |expert| %>
					<p><a href="/users/<%= expert.id %>"><%= expert.name %></a><br />
				<% end %>
				</div>
				<div class="ilb">
				<h3>Grupo Expertos en Herpetos:</h3>

				<% @herpetos_experts.each do |expert| %>
					<p><a href="/users/<%= expert.id %>"><%= expert.name %></a><br />
				<% end %>
				</div>
				<div class="ilb">
				<h3>Grupo Expertos en Mamíferos:</h3>

				<% @mamiferos_experts.each do |expert| %>
					<p><a href="/users/<%= expert.id %>"><%= expert.name %></a><br />
				<% end %>
				</div>
				<div class="ilb">
				<h3>Grupo Expertos en Peces:</h3>

				<% @peces_experts.each do |expert| %>
					<p><a href="/users/<%= expert.id %>"><%= expert.name %></a><br />
				<% end %>
				</div>
			</div>
	</article>	
</div>

app/views/home/send_message.js.erb
$("#mailform").html("<p>Su mensaje ha sido enviado con éxito. ¡Gracias!</p>");

app/views/home/show.html.erb
<div class="homeline">
	<div class="contenedor">
		<div class="hlcol1">
			<h1>BioModelos</h1>
			<h2>Aplicación de Consulta y Validación</br>
			de Modelos de Distribución de</br>
			Especies en Colombia<a href="#vermas" class="vermas">+ ver más</a></h2>
			<div class="lbabimg2"></div>
		</div>
		<div class ="intro2" id="banner-slide">

			<ul class="bjqs">
          		<li>
          		<!-- <a class="twitter-timeline"  href="https://twitter.com/BioModelos" data-widget-id="527190072597049344" data-chrome="noheader nofooter">Tweets by @BioModelos</a>
            	<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script> -->
					<aside class="activity2">
						<h5>Actividad biomodelos</h5>
						<ul>
					        <li class="actfeed">
								<div class="minavatar"><%= image_tag("minavatar2.jpg") %></div>
					        	<div class="clearfix">
						            <a class="feeduser" href="#">LBAB</a>
						            <div class="feedtime">02/12/2014</div>
						        </div>
					            <p class="feedcontent">Lanzamiento oficial de BioModelos en el Marco del IV Congreso Colombiano de Zoología - Cartagena, 2 de diciembre de 2014</p>
					        </li>
					        <li class="actfeed">
								<div class="minavatar"><%= image_tag("minavatar2.jpg") %></div>
					        	<div class="clearfix">
						            <a class="feeduser" href="#">LBAB</a>
						            <div class="feedtime">06/11/2014</div>
						        </div>
					            <p class="feedcontent">1er Taller de Validación de Distribución de Peces - Bogotá, 6 de noviembre de 2014</p>
					        </li>
					        <li class="actfeed">
								<div class="minavatar"><%= image_tag("minavatar2.jpg") %></div>
					        	<div class="clearfix">
						            <a class="feeduser" href="#">LBAB</a>
						            <div class="feedtime">04/11/2014</div>
						        </div>
					            <p class="feedcontent">1er Taller de Validación de Distribución de Herpetos - Medellín, 4 y 5 de noviembre de 2014</p>
					        </li>
					        <li class="actfeed">
								<div class="minavatar"><%= image_tag("minavatar2.jpg") %></div>
					        	<div class="clearfix">
						            <a class="feeduser" href="#">LBAB</a>
						            <div class="feedtime">16/10/2014</div>
						        </div>
					            <p class="feedcontent">1er Taller de Validación de Distribución de Plantas Invasoras - Bogotá, 16 y 17 de octubre de 2014</p>
					        </li>
					        <li class="actfeed">
								<div class="minavatar"><%= image_tag("minavatar2.jpg") %></div>
					        	<div class="clearfix">
						            <a class="feeduser" href="#">LBAB</a>
						            <div class="feedtime">08/10/2014</div>
						        </div>
					            <p class="feedcontent">1er Taller de Validación de Distribución de Mamíferos - Armenia, 8 y 9 de octubre de 2014</p>
					        </li>
					        <li class="actfeed">
								<div class="minavatar"><%= image_tag("minavatar2.jpg") %></div>
					        	<div class="clearfix">
						            <a class="feeduser" href="#">LBAB</a>
						            <div class="feedtime">30/09/2014</div>
						        </div>
					            <p class="feedcontent">1er Taller de Priorización de Sitios de Invernada y de Paso de la Reinita Canadiense – Bogotá, 30 de septiembre al 3 de octubre de 2014</p>
					        </li>
					        <li class="actfeed">
								<div class="minavatar"><%= image_tag("minavatar2.jpg") %></div>
					        	<div class="clearfix">
						            <a class="feeduser" href="#">LBAB</a>
						            <div class="feedtime">24/09/2014</div>
						        </div>
					            <p class="feedcontent">Después de una depuración de datos, se corrieron nuevos modelos en el mes de agosto llevando el número de especies modeladas a 5786</p>
					        </li>
					        <li class="actfeed">
								<div class="minavatar"><%= image_tag("minavatar2.jpg") %></div>
					        	<div class="clearfix">
						            <a class="feeduser" href="#">LBAB</a>
						            <div class="feedtime">26/06/2014</div>
						        </div>
					            <p class="feedcontent">Realizado segundo taller de Aves Acuaticas en Bogotá</p>
					        </li>
					        <li class="actfeed">
								<div class="minavatar"><%= image_tag("minavatar2.jpg") %></div>
					        	<div class="clearfix">
						            <a class="feeduser" href="#">LBAB</a>
						            <div class="feedtime">25/06/2014</div>
						        </div>
					            <p class="feedcontent">Se actualizaron 81 especies y agregaron 5 nuevas especies de aves acuáticas</p>
					        </li>
					        <li class="actfeed">
								<div class="minavatar"><%= image_tag("minavatar2.jpg") %></div>
					        	<div class="clearfix">
						            <a class="feeduser" href="#">LBAB</a>
						            <div class="feedtime">15/05/2014</div>
						        </div>
					            <p class="feedcontent">Rediseños a la aplicación se ponen en línea</p>
					        </li>
					        <li class="actfeed">
								<div class="minavatar"><%= image_tag("minavatar2.jpg") %></div>
					        	<div class="clearfix">
						            <a class="feeduser" href="#">LBAB</a>
						            <div class="feedtime">24/04/2014</div>
						        </div>
					            <p class="feedcontent">Realizado primer taller de Aves Acuaticas en Cali</p>
					        </li>
					        <li class="actfeed">
								<div class="minavatar"><%= image_tag("minavatar2.jpg") %></div>
					        	<div class="clearfix">
						            <a class="feeduser" href="#">LBAB</a>
						            <div class="feedtime">22/05/2014</div>
						        </div>
					            <p class="feedcontent">16 nuevas especies agregadas a BioModelos</p>
					        </li>
					        <li class="actfeed">
								<div class="minavatar"><%= image_tag("minavatar2.jpg") %></div>
					        	<div class="clearfix">
						            <a class="feeduser" href="#">LBAB</a>
						            <div class="feedtime">05/03/2014</div>
						        </div>
					            <p class="feedcontent">Presentación de la herramienta al proyecto Ecopetrol en Choachi</p>
					        </li>
					        <li class="actfeed">
								<div class="minavatar"><%= image_tag("minavatar2.jpg") %></div>
					        	<div class="clearfix">
						            <a class="feeduser" href="#">LBAB</a>
						            <div class="feedtime">03/03/2014</div>
						        </div>
					            <p class="feedcontent">Primera versión Beta de BioModelos en línea</p>
					        </li>
					    </ul>
					</aside>
				</li>
				<li><!--<a href="http://biomodelos.humboldt.org.co/models/visor?species_id=4239">--><%= image_tag("mini-marzo-2015.jpg") %><!--</a>--></li>
				<li><%= image_tag("fotobogota.jpg") %></li>
		        <li><%= image_tag("info.png") %></li>
	        </ul>
		</div>
	</div>
</div>

<div class="clearfix"></div>
<article class="opciones">
	<div class="contenedor">

		<%= link_to models_visor_path do %>
		<div class="op">
			<div class="imginicio op1"></div>
			<div class="fondoinicio">
				<h1>CONSULTA</h1>
				<h6>Consulta las hipótesis de distribución disponibles por especie.</h6>
			</div>
		</div>
		<% end %>

		<%= link_to new_user_session_path do %>
		<div class="op">
			<div class="imginicio op2"></div>
			<div class="fondoinicio">
				<h1>INGRESA</h1>
				<h6>Une tu conocimiento a la red de expertos.</h6>
			</div>
		</div>
		<% end %>

		<%= link_to models_visor_path do %>
		<div class="op">
			<div class="imginicio op3"></div>
			<div class="fondoinicio">
				<h1>CONTRIBUYE</h1>
				<h6>Mejora los modelos evaluando y editando las hipótesis de distribución.</h6>
			</div>
		</div>
		<% end %>

		<% if user_signed_in? %>
        <%= link_to groups_path do %>
		<div class="op">
			<div class="imginicio op4"></div>
			<div class="fondoinicio">
				<h1>INTERACTUA</h1>
				<h6>Intercambia información con expertos en tus grupos taxonómicos de interés.</h6>
			</div>
		</div>
        <% end %>
        <% else %>
			<div class="op">
				<div class="imginicio op4"></div>
				<div class="fondoinicio">
					<h1>INTERACTUA</h1>
					<h6>Intercambia información con expertos en tus grupos taxonómicos de interés.</h6>
				</div>
			</div>
        <% end %>

		
	</div>
</article>

	<div class="homeline2">
	</div>

	<div class="contenedor padbtm clearfix" id="vermas">
		<section class="introtext">
			<h1>¿QUÉ HACE BIOMODELOS?</h1>
			<h2>Mapas integrativos entre expertos y modelos de distribución.</h2>
			<h5>BioModelos es una herramienta digital que permite la <strong>comunicación entre expertos</strong> en biodiversidad para el desarrollo de modelos de distribución de las especies existentes en Colombia de forma colaborativa y abierta.</br></br>
			Esta iniciativa surge con el fin de acercar a investigadores, instituciones gubernamentales, ONGs y ciudadanos, a una <strong>información precisa y validada</strong> por expertos sobre la distribución de especies en Colombia, que sirva como referencia para estudios y la toma de decisiones sobre biodiversidad.</h5>
		</section>
		<div class="variables">
			<div class="variable1 var1">
				<h3>MODELOS DE</br>
					DISTRIBUCIÓN</h3>
					<p>Se ofrecen modelos estadísticos fácilmente actualizables</p>
			</div>
			<div class="variable2 var2">
			</div>
			<div class="variable1 var1b">
				<h3>COMUNIDAD</br>
					DE EXPERTOS</h3>
					<p>Validación por el grupo de expertos de la comunidad</p>
			</div>
			<div class="variable3">
				<div class="var3a">
					<h4>EVALUAR</h4>
					<p>Identificar los mejores modelos de especies</p>
				</div>
				<div class="var3b">
					<h4>EDITAR</h4>
					<p>Ocurrencias, sobrepredicción o subpredicción</p>
				</div>
				<div class="var3c">
					<h4>ALERTAR</h4>
					<p>Reportar inconsistencias en los datos</p>
				</div>
			</div>
		</div>
	</div>

	<div class="homeline3">
	</div>

	<div class="contenedor padbtm" id="vermas2">
		<section class="introtext">
			<h1>¿QUIÉNES NOS APOYAN?</h1>
			<h2>Proyectos, colaboraciones y datos.</h2>
			<h5>BioModelos parte del marco de los proyectos “Componente biótico del Mapa de Ecosistemas de Colombia” e “Insumos para la Delimitación de Ecosistemas Estratégicos: Páramos y Humedales” impulsados por el  <strong>Ministerio de Ambiente y Desarrollo Sostenible</strong> y el <strong>Fondo Adaptación</strong> del Ministerio de Hacienda y Crédito Público.</h5>
		</section>
		<div class="patro">
		<h4>PATROCINADORES</h4>
			<a href="http://www.minambiente.gov.co" target="_blank"><%= image_tag("minamb.png") %></a>
			<a href="http://sitio.fondoadaptacion.gov.co" target="_blank"><%= image_tag("fondologo.png") %></a></br>
		<h4>COLABORADORES</h4>
			<a href="http://www.sibcolombia.net" target="_blank" title="Sistema de información sobre biodiversidad de Colombia"><%= image_tag("logosib.png") %></a>
			<a href="http://calidris.org.co" target="_blank" title="Asociación para el estudio y conservación de las aves acuáticas en Colombia"><%= image_tag("logocalidris.png") %></a>
			<a title="Sociedad Colombiana de Mastozoología"><%= image_tag("logoscm.png") %></a>
			<a href="http://www.acherpetologia.org" target="_blank" title="Asociación Colombiana de Herpetología"><%= image_tag("logoach.png") %></a>
		</div>
	</div>


<div class="clearfix fixfooter"></div>
<a href="#vermas2" class="flechahome"></a>

<script type="text/javascript">
$(window).scroll(function() {
    var pxFromBottom = 100;
    if ($(window).scrollTop() + $(window).height() > $(document).height() - pxFromBottom) {
        $('.flechahome').fadeOut('slow');
    } else {
        $('.flechahome').fadeIn('slow')
    }
});

</script>